// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lN9oVh5YXdOCaxWmcBzOReKzOLiuRRw',
    appId: '1:33489120151:web:aecbfae5bd3b85a0fb32d2',
    messagingSenderId: '33489120151',
    projectId: 'podoaplus',
    authDomain: 'podoaplus.firebaseapp.com',
    databaseURL: 'https://podoaplus-default-rtdb.firebaseio.com',
    storageBucket: 'podoaplus.appspot.com',
    measurementId: 'G-FT47B5N1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJj8x1DKg7EnchNCZ4HQbK2kHht2a7zq0',
    appId: '1:33489120151:android:681563ebd54f3b9bfb32d2',
    messagingSenderId: '33489120151',
    projectId: 'podoaplus',
    databaseURL: 'https://podoaplus-default-rtdb.firebaseio.com',
    storageBucket: 'podoaplus.appspot.com',
  );
}
